(library
 (name type)
 (modules type))

(library
 (name utils)
 (modules utils))

(library
 (name mapgen)
 (modules mapgen)
 (libraries utils type domainslib))

(library
 (name village)
 (modules village)
 (libraries mapgen type mapmanage))

(library
 (name decision)
 (modules decision)
 (libraries mapgen mapmanage type village utils))

(library
 (name score)
 (modules score)
 (libraries village type mapgen))

(library
 (name game)
 (modules game)
 (libraries
  village
  mapgen
  type
  newgen
  score
  yojson
  dumpmap
  decision
  mutation
  foret))

(library
 (name dumpmap)
 (modules dumpmap)
 (libraries mapgen mapmanage type yojson village newgen))

(library
 (name mapmanage)
 (modules mapmanage)
 (libraries mapgen type))

(library
 (name newgen)
 (modules newgen)
 (libraries village type))

(library
 (name mutation)
 (modules mutation)
 (libraries village type utils mapgen))

(library
 (name foret)
 (modules foret)
 (libraries yojson type village mapgen))
